In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)
print(np.__version__)

/da1/fenxi/install/anaconda2/envs/python3tf/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


1.5.0
1.14.1


In [2]:
c = tf.constant(np.random.randn(2,3,4),dtype=tf.float32,shape=[2,3,4])

In [3]:
u = tf.unstack(c)

In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(c))
    print('--------------')
    print(type(sess.run(u)))

[[[-0.39122427 -1.121834    1.0883973   0.00352599]
  [ 0.41153267  1.9039953  -0.6072528  -0.8965254 ]
  [-0.26732522  1.377852   -1.2398587   0.13800064]]

 [[-0.41403374 -0.6909946  -0.2108212   2.7545612 ]
  [-0.7398098   2.3503451  -0.8110865   0.29192382]
  [ 1.1420683  -0.41518515  0.29538122 -1.2099715 ]]]
--------------
<class 'list'>
