In [1]:
import numpy as np
import tensorflow as tf

/usr/lib64/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# 四则运算

### add() 和 +

In [61]:
x = tf.constant([[1,2],[1,2]])
y = tf.constant([2,1])
with tf.Session() as sess:
    print sess.run(tf.add(x,y))
    print sess.run(x + y)

[[3 3]
 [3 3]]
[[3 3]
 [3 3]]


### subtract() 和 -

In [64]:
x = tf.constant([[1,2],[1,2]])
y = tf.constant([2,1])
with tf.Session() as sess:
    print sess.run(tf.subtract(x,y))
    print sess.run(x - y)

[[-1  1]
 [-1  1]]
[[-1  1]
 [-1  1]]


### multiply()

In [68]:
x = tf.constant([[1,2,3],[4,5,6]])
y = tf.constant([[2],[3],[4]])
z = tf.constant([[3,2,1],[6,5,4]])
with tf.Session() as sess:
    print sess.run(tf.matmul(x,y)) # 矩阵乘法
    print sess.run(tf.multiply(x,z)) # 按位相乘
    print sess.run(x * z) # 按位相乘

[[20]
 [47]]
[[ 3  4  3]
 [24 25 24]]
[[ 3  4  3]
 [24 25 24]]


### div divide 和 /

In [8]:
x = tf.constant([[1,2,3],[4,5,6]])
y = tf.constant([[1,4,9],[2,1,2]])
a = tf.constant([[1,2,3],[4,5,6]], dtype=tf.float32)
b = tf.constant([[1,4,9],[2,1,2]], dtype=tf.float32)
with tf.Session() as sess:
    print sess.run(tf.div(x,y)) 
    print sess.run(tf.divide(x,y))
    print sess.run(x / y)
    print '----------------------'
    print sess.run(tf.div(a, b))
    print sess.run(tf.divide(a, b))
    print sess.run(a / b) 

[[1 0 0]
 [2 5 3]]
[[1.         0.5        0.33333333]
 [2.         5.         3.        ]]
[[1 0 0]
 [2 5 3]]
----------------------
[[1.         0.5        0.33333334]
 [2.         5.         3.        ]]
[[1.         0.5        0.33333334]
 [2.         5.         3.        ]]
[[1.         0.5        0.33333334]
 [2.         5.         3.        ]]


# ------------------------------------------------------------------------------

In [11]:
X = tf.placeholder(tf.float32, [None, 784])
X_img = tf.reshape(X, [-1,28,28,1])
Y = tf.placeholder(tf.float32, [None, 10])

### tile(values=, shape=)

In [46]:
t1 = tf.constant([1,2,3])
t2 = tf.constant([4,5,6])
t3 = tf.tile([t1, t2],[1,1])
with tf.Session() as sess:
    print sess.run(t3)

[[1 2 3]
 [4 5 6]]


### concat(values=, concat_dim=)

In [50]:
t1=tf.constant([[1,2,3]])  
t2=tf.constant([[4,5,6]])
t3 = tf.concat([t1, t2], 0) #==> [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
t4 = tf.concat([t1, t2], 1) #==> [[1,2,3,7,8, 9], [4,5,6,10,11, 12]]
with tf.Session() as sess:
    print sess.run(t3)
    print sess.run(t4)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


### reduce_sum(tensor=,axis=,keep_dims=)

In [51]:
x = tf.constant([[1,2,3],[4,5,6]])
y = tf.reduce_sum(x,axis=0)
yk = tf.reduce_sum(x,axis=0,keep_dims=True)
z = tf.reduce_sum(x,axis=1)
with tf.Session() as sess:
    print sess.run(x)
    print sess.run(y)
    print sess.run(yk)
    print sess.run(z)

[[1 2 3]
 [4 5 6]]
[5 7 9]
[[5 7 9]]
[ 6 15]
