In [1]:
import tensorflow as tf
import numpy as np

/usr/lib64/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


功能：通过equation进行矩阵乘法。
输入：equation：乘法算法定义。
* 矩阵乘
 einsum('ij,jk->ik', m0, m1)  # output[i,k] = sum_j m0[i,j] * m1[j, k]
* 点乘
 einsum('i,i->', u, v)  # output = sum_i u[i]*v[i]
* 向量乘
 einsum('i,j->ij', u, v)  # output[i,j] = u[i]*v[j]
* 转置
 einsum('ij->ji', m)  # output[j,i] = m[i,j]
* 批量矩阵乘
 einsum('aij,ajk->aik', s, t)  # out[a,i,k] = sum_j s[a,i,j] * t[a, j, k]


In [6]:
m1 = [[1,2],[3,4],[5,6]]
m2 = [[1,0,0],[0,1,0]]

In [7]:
x = tf.Variable(m1, tf.float32)
y = tf.Variable(m2, tf.float32)

In [8]:
z = tf.einsum('ij,jk->ik',x,y)

In [9]:
z.get_shape()

TensorShape([Dimension(3), Dimension(3)])

In [10]:
with tf.Session() as sess:
    print sess.run(z, feed_dict={x:m1,y:m2})

[[1 2 0]
 [3 4 0]
 [5 6 0]]
