In [1]:
import tensorflow as tf

/usr/lib64/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [7]:
var = tf.constant([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
sess = tf.Session()
sess.run(tf.global_variables_initializer())

### tf.gather()

In [8]:
gat = tf.gather(params=var, indices=[0,1])
print sess.run(gat)

[[1 2 3]
 [4 5 6]]


### tf.slice()

In [9]:
sli = tf.slice(input_=var, begin=[1,0], size=[2,3])
print sess.run(sli)

[[4 5 6]
 [7 8 9]]


### tf.split(value, num_or_size_splits, axis=0, num=None, name='split')
Docstring:
Splits a tensor into sub tensors.

In [10]:
spl = tf.split(var, 2)
print sess.run(spl)

[array([[1, 2, 3],
       [4, 5, 6]], dtype=int32), array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)]
